# Generated by Django 4.1.6 on 2023-03-31 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nixie_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
