# Generated by Django 4.1.6 on 2023-04-08 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nixie_app', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='image1',
            field=models.ImageField(blank=True, upload_to='products/<django.db.models.fields.SlugField>'),
        ),
        migrations.AddField(
            model_name='product',
            name='image2',
            field=models.ImageField(blank=True, upload_to='products/<django.db.models.fields.SlugField>'),
        ),
        migrations.AddField(
            model_name='product',
            name='image3',
            field=models.ImageField(blank=True, upload_to='products/<django.db.models.fields.SlugField>'),
        ),
        migrations.AddField(
            model_name='product',
            name='lamp_currency',
            field=models.CharField(blank=True, choices=[('4', '4'), ('6', '6')], db_index=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='lamp_type',
            field=models.CharField(blank=True, choices=[('ИН-8', 'ИН-8'), ('ИН-12', 'ИН-12'), ('ИН-14', 'ИН-14'), ('ИН-16', 'ИН-16'), ('ИН-17', 'ИН-17'), ('ИН-18', 'ИН-18')], db_index=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='length',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='material',
            field=models.CharField(blank=True, choices=[('Ясень', 'Ясень'), ('Дуб', 'Дуб'), ('Бук', 'Бук')], db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
