# Generated by Django 4.1.6 on 2023-04-08 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nixie_app', '0006_alter_product_available_alter_product_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='view',
            field=models.CharField(auto_created='string', blank=True, choices=[('string', 'строка'), ('card', 'карточка')], db_index=True, max_length=50),
        ),
    ]
