# Generated by Django 4.1.6 on 2023-04-09 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nixie_app', '0008_alter_product_view'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='view',
        ),
    ]
