# Generated by Django 4.0.4 on 2023-05-12 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nixie_app', '0010_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review_text',
            field=models.CharField(db_index=True, max_length=500, verbose_name='Отзыв'),
        ),
    ]
