# Generated by Django 4.0.4 on 2023-06-04 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nixie_app', '0012_alter_review_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name',), 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
    ]
